---
title: "Entanglements"
author: "Sam Woodman"
date: "1/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Goal: Examine monthly risk histograms relative to entanglement report locations.



```{r, message=FALSE}

library(dplyr)
library(ggplot2)
library(readxl)
library(tibble)

source("User_script_local.R")
if (user == "JS") {
  file.ent
  
} else if (user == "SMW") {
  file.ent <- "../raimbow-local/Data/Entanglements/Entanglements_known_gear_set_location.xlsx"
  
} else {
  stop("User not recognized")
}
```

## Data import and processing

Read in entanglement data, and select relevant columns. Then assign each entanglement to a region, using Gear_Set_County to determine region.

```{r}
### Make data frame relating regions and counties
# reg.names <- c("CA-S", "CA-SCen", "CA-Cen", "CA-N", "OR", "WA")
# reg.bound <- c(32.5, 34.4, 36.3, 38.76683, 42, 46.25, 50)
# 
# reg.bound <- c(
#   42, 41.5, 40, 38.83, 38.3, 
#   37.8, 37.7, 37.1, 36.83, 35.8, 
#   35, 34.375, 34, 33.75, 33.35, 
#   32.5
# )

# Monterey definitely has some are in CA-SCen too
reg.list <- list(
  "Del_Norte" = "CA-N", "Humboldt" = "CA-N", "Mendocino" = "CA-N", 
  "Sonoma" = "CA-Cen", "Marin" = "CA-Cen", "San_Francisco" = "CA-Cen",
  "San_Mateo" = "CA-Cen", "Santa_Cruz" = "CA-Cen", "Monterey" = "CA-Cen", 
  "San_Luis_Obispo" = "CA-SCen", "Santa_Barbara" = "CA-SCen", 
  "Ventura" = "CA-S", "Los_Angeles" = "CA-S", "Orange" = "CA-S", 
  "San_Diego" = "CA-S"
)

county.reg <- data.frame(region = t(as.data.frame(reg.list)), 
                         stringsAsFactors = FALSE) %>% 
  rownames_to_column(var = "county") %>% 
  mutate(county = gsub("_", " ", county, ))


### Get year-month factor levels
ym.levels <- tibble(
  year = c(rep(2009, 2), sapply(2010:2017, rep, 12), rep(2018, 7)),
  month = sprintf("%02d", c(11, 12, rep(1:12, 8), 1:7))
) %>% 
  mutate(ym = paste(year, month, sep = "_"))


### Read in and process entanglement data
x.orig <- read_xlsx(file.ent)

x <- x.orig %>% 
  select(CaseID, Year, Month, Report_Lat, Report_Long, Report_County, 
         Gear_Set_County, Gear_Set_Location_State, Timing) %>% 
  left_join(county.reg, by = c("Gear_Set_County" = "county")) %>% 
  mutate(Gear_Set_County = as.factor(Gear_Set_County), 
         region = factor(region, levels = c("WA", "OR", "CA-N", "CA-Cen", "CA-SCen")), 
         ym = factor(paste(Year, sprintf("%02d", Month), sep = "_"), levels = ym.levels$ym)) %>% 
  filter(!is.na(ym))



# x.summ <- x %>% 
#   mutate(ym = factor(ym, levels = x.ym.levels$ym)) %>% 
#   group_by(ym)
```

Make some histograms of...

```{r, fig.height=4, fig.width=10}
x.max <- length(levels(x$ym))
x.lab.idx <- seq(1, to = x.max, by = 3)
x.lab <- sort(levels(x$ym))[x.lab.idx]
vert.lines <- seq(0.5, to = x.max, by = 12)

ggplot(x, aes(x = ym, fill = region)) + 
  geom_bar() + 
  geom_vline(xintercept = vert.lines, col = "black", lwd = 0.35) + 
  scale_fill_brewer(palette = "Set1", name = "Region", drop = FALSE) + 
  ggtitle("CA DC confirmed and known-set-location entanglements") +
  xlab("Year_Month") +
  ylab("Entanglements") +
  scale_x_discrete(drop = FALSE, breaks = x.lab) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.4),
        legend.justification = "top")
```

