rm(list = ls())

library(lubridate)
library(tidyverse)
library(data.table)
library(sf)
library(magrittr)
library(maps) # for map background
library(viridis)
library(here)
library(janitor)

### read in data with tickets/VMS/vlengths matched, if ready

dcrb_vms_tix_analysis <- read_rds(
  "~/Documents/RAIMBOW/Processed Data/VMS/vms_all_interpolated_w_grd_vlengths.RDS"
)
glimpse(dcrb_vms_tix_analysis)

# load vessel length keys and bind

vessel_length_key_df <- list.files(path = "~/Documents/RAIMBOW/Processed Data/vessel length keys", full.names=TRUE, pattern = ".rds") %>%
  map_dfr(read_rds)
glimpse(vessel_length_key_df)

# load original vessel registration table from pacfin
vessel_reg <- read_csv("/Users/jameal.samhouri/Documents/RAIMBOW/Raw Data/PacFIN/CA_2009_2018_vesselreg.csv")
glimpse(vessel_reg)

# read in CA permit data

permits_cdfw <- read_csv("/Users/jameal.samhouri/Documents/RAIMBOW/Raw Data/CDFW/CDFW_DcrabPermits_2009-2018.csv") #%>%
  #clean_names()
glimpse(permits_cdfw)
names(permits_cdfw)
tier_key <- read_csv("/Users/jameal.samhouri/Documents/RAIMBOW/Raw Data/CDFW/TrapTierNumberKey.csv")

#VESSEL_REGISTRATION_ID links the Fish Ticket and Vessel Registration tables.  This field is artificially generated by PACFIN software. 
#The Vessel Registration and Permit tables can be linked by the following fields:
  #AGENCY_CODE (agency_code)
  #VESSEL_NUM (we call this drvid, legacy name)
  #REGISTRATION_YEAR (vessel table) and PERMIT_YEAR (permit table)
#PERMIT_ID links the PERMITS and PERMIT_OWNERS tables.  This is also artificially generated by PacFIN. 

length(which(permits_cdfw$`FG VESSEL ID` %in% vessel_reg$VESSEL_NUM == TRUE))
length(which(permits_cdfw$`FG VESSEL ID` %in% dcrb_vms_tix_analysis$drvid == TRUE))

unique(sort(permits_cdfw$`FG VESSEL ID`))[1:10]
unique(sort(vessel_reg$VESSEL_NUM))[1:10]
unique(sort(dcrb_vms_tix_analysis$drvid))[1:10]

range(permits_cdfw$`FG VESSEL ID`)
range(vessel_reg$VESSEL_NUM)
range(dcrb_vms_tix_analysis$drvid)

# following call with CDFW and PSMFC on 080720
length(which(permits_cdfw$`FG VESSEL ID` %in% vessel_reg$REGISTRATION_NUM == TRUE)) #4483
length(which(permits_cdfw$`FG VESSEL ID` %in% vessel_reg$REGISTRATION_NUM == TRUE))/length(unique(vessel_reg$REGISTRATION_NUM)) #0.766
